[project]
name = "kwod-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arrow>=1.3.0",
    "httpx>=0.28.1",
    "openai>=1.100.1",
    "python-dotenv>=1.1.1",
    "selectolax>=0.3.33",
]
